### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by avsm** [ocaml-community/meta#10]
I'd like to propose the [yaml](https://github.com/avsm/ocaml-yaml) bindings for community maintenance.  They most already work, but need to keep up with Yaml versions, and some of the more advanced features like Yaml aliases need to be implemented carefully.

**Comment by pmetzger** [comment]
Seems good to me. I'll send you an invite for the github organization shortly.

**Comment by pmetzger** [comment]
Okay, are you ready to move it over? If so, feel free to tell github to migrate the repo over, you have the right permissions at this end.

**Comment by pmetzger** [comment]
@avsm I note this has sat for a while. Did you give up on the idea?

**Comment by avsm** [comment]
Not had the time yet. It had a Windows CI hanging off it that also needs to be setup. It's on my todo list...

**Comment by pmetzger** [comment]
Cool. We can handle it whenever you like.

**Comment by avsm** [comment]
There are too many downstream dependencies on yaml to hand it off for now. I'll probably move it into the mirage/ organisation from avsm/ as it's used in Irmin as well. Closing this out...
