### ISSUE TITLE
How to designate maintaners for new projects

### ISSUE THREAD

**Issue by Drup** [ocaml-community/meta#12]
In [this post](https://discuss.ocaml.org/t/ocaml-community-github-organization/2413/33?u=drup), I expressed the fact that projects should still have dedicated maintainers.

I think new projects should always come with a sort of "Call for Maintainship" and that having a volunteer for the job would be a condition for bringing in ocaml-community. Of course, not all projects require the same amount of attention, and some of them just requires small updates to compile on OCaml versions, but even then, we should have one person that takes ownership. A call for maintainship would of course make explicit the state of the project.

Ideally, the process should not be *too* rigid, of course, so I'm not sure exactly how to make it nice in practice. We should definitely send out the calls on various mediums, such as discuss/planet on a regular basis.

**Comment by pmetzger** [comment]
So we should probably ask whomever is proposing bringing in a project if they're willing to be the initial maintainer. I think that some of the time they probably will be.

We may also want to pick a slightly different name, or condition the expectations about what a maintainer is. Someone (or some set of people) has to be responsible for handling pull requests, keeping the code building on new versions of OCaml, and meaningfully responding to critical issues (say security bugs), but that's different from (say) being willing to implement interesting new features, which is a big part of what one normally expects of a maintainer. For new features, I'd be expecting that we'd depend more on community involvement.

I'd say that, ideally, every project would have at least one person in this position, acting as gatekeeper for prompt responses on pull requests, and making sure that code continues to build with every OCaml release. For significant projects, preferably we'd have a couple.

**Comment by Drup** [comment]
> We may also want to pick a slightly different name, or condition the expectations about what a maintainer is. [...]

That should really be on a project-per-project basis. Either the project is already stable and can be in maintenance mode, without new features, or it needs some significant work that the current maintainer can not provide. This should be explicitly formulated by the person who want to transfer the repository. I don't think we should try to make a blanket statement about what a maintainer should do in general, except "keep the thing functional".

**Comment by bluddy** [comment]
I think one thing we definitely need to consider is that being maintainer of a project means you have to dive into the code and understand it. That's the big bottleneck here, and the reason we can't let go of the people bringing in the projects. We're sort of talking about collecting a lot of projects as if we're just talking about collecting articles, when in fact each project brings with it a ton of complexity. We have to think about how to keep the complexity level down so it doesn't overwhelm our very limited resources.

Some ideas:
1. Projects coming in that are not abandoned should step up their documentation efforts. A document walking through the design should be recommended if not required.
2. The more we know about the plans of the maintainer, the better. What were they planning on doing next but didn't get to? What can be done to make the project easier to maintain? Are there community libraries that could replace proprietary code and make the code simpler?
3. I agree with @Drup that we need to have some good way to communicate that a project needs attention/needs a new maintainer. This may be as easy as opening an issue with a unique tag ('call for help'/'call for maintainers') that's visible in a search over the organization.
4. Nobody new should be able to become a maintainer of a project without first showing some competence with its code. This means submitting a pull request that is accepted and shows that they understand the working of the codebase. It's better to have no maintainer than a maintainer who has no idea what he's doing IMO.

**Comment by pmetzger** [comment]
@bluddy We have to be a bit careful here. If we get _too_ choosy/demand too much then we may not find ourselves able to adopt anything. There are very few projects that really have a design walkthrough. I agree such a document is a wonderful thing and I don't mind _suggesting_ them.

I also think a "To Do" list from the maintainer ("these are things that should be added to the package going forward") would be great, though again, we can't always presume that we'll get them.

For (4), I don't agree that no maintainer than a maintainer who doesn't have deep familiarity is better. I can probably reasonably evaluate (for example) submissions to fix strings to bytes where appropriate in many packages that I don't otherwise understand, and that fix alone would make a lot of abandoned useful packages suddenly widely useful again. I can also write documentation quite successfully for code that I don't deeply understand. I agree that it is _ideal_ to have a person maintaining a package who really knows the code, but we don't always get ideal in the real world.

**Comment by Drup** [comment]
Keep in mind that most packages are small (we are not talking lwt-size packages here) and adopting one is not such a big initial effort, but more of a commitment to take time in the future.

So, if we have at least one person in charge of each given package, we don't have to collectively manage the global complexity of each package.  This would naturally fill 1 and 2, by simply not assuming all members of ocaml-community will have to look at the project.

> Nobody new should be able to become a maintainer of a project without first showing some competence with its code. [...] It's better to have no maintainer than a maintainer who has no idea what he's doing IMO.

I would tend to give people the benefit of the doubt in most cases, especially in not-so-critical packages. In the worse case, old versions are in opam and reverts are a thing.

**Comment by pmetzger** [comment]
BTW, to take a good example: [CIL](https://github.com/cil-project/cil) has been abandoned even though it's widely used in academia. The project owners gave me commit access recently so I could pull some strings to bytes fixes. If I got them to put it under ocaml-community, I could probably reasonably evaluate pull requests for typical maintenance, but I'm absolutely not deeply enough into the code to claim to being truly familiar with the code.

**Comment by Drup** [comment]
I agree with @pmetzger that we should encourage people to maintain, and not smother them with constraints. That's why I also don't want a high bar for "minimum maintainer responsibilities". If someone else comes along and want to be more active, well, that's exactly why ocaml-community is here, isn't it ? :)

I just want the rules to be clear to avoid the landfill effects found in several such community-directed repositories, we do not have the means to ensure that every project is a shining beacon of perfect open source software.

**Comment by pmetzger** [comment]
Yah, there's a happy medium. No landfill, but also not requirements so excessive that they're impossible to achieve.

**Comment by Drup** [comment]
Can we finish this ? I really think we should figure this out before getting new packages. My opinion would be that a package need to find an actual, active maintainer *before* being merged in ocaml-community.

**Comment by pmetzger** [comment]
I think we have the issue settled in our heads, but what would finishing the issue consist of? Creating a document with the information in it? Which document would be appropriate? (I'm asking seriously.)

**Comment by Drup** [comment]
Well, we should decide formally what should be the procedure for new project submissions, find a decent channel to request maintaners. There is the responsability question, which was asked before. I don't want to impose constraint, but one important responsibility, that is often lacking in "maintenance mode" software, is to actually make the releases in the timely manner.

Anyway, there are lot's of details to decide, but I guess we should start by adding a new section "How to porpose a new package" to the manifesto (it's in the FAQ now, it should on its own).

**Comment by pmetzger** [comment]
See #17. It's a strawman. I'll accept any reasonable edits.

**Comment by pmetzger** [comment]
@Drup was #17 enough for this, or do we need more before we close it?

**Comment by Drup** [comment]
It's probably enough until we have more experience!
