### ISSUE TITLE
Rename "manifesto" to something better

### ISSUE THREAD

**Issue by pmetzger** [ocaml-community/meta#14]
Although it's precedented from the elm-community and coq-community organizations, the "manifesto" repository should probably be named something clearer, like "admin" or some such. Opinions solicited.

**Comment by rizo** [comment]
`ocaml-community/admin` or `ocaml-community/meta` would be better indeed than `ocaml-community/manifesto`.

We should still have a "Manifesto" section in the README though.

**Comment by pmetzger** [comment]
I think "meta" seems like a good name. And yes, we'd leave the README as it is for now.

**Comment by pmetzger** [comment]
I've renamed the repository to `meta`.
