### ISSUE TITLE
OCaml Cstruct

### ISSUE THREAD

**Issue by XVilka** [ocaml-community/meta#19]
## Propose to move a project to ocaml-community ##

**Project name:** ocaml-cstruct

**Initial author(s):**

**Current URL:** https://github.com/mirage/ocaml-cstruct

**License:** ISC License

**Description:** Access C-like structures directly from OCaml

**Do the current maintainer(s) agree with the move:** unknown - no response, project looks dead

**New maintainer:** I am a volunteer

**Comment by Drup** [comment]
Hold your horses. 

1. cstruct is part of mirage, and they already have all the infrastructure needed to cycle through maintainers and review contributions. If you want to propose yourself for maintaner, you can do it there already.
2. You didn't even asked the maintainers about a transfer! 
3. Your assessment of the project being dead seems to be based on bunch of reports you made 11 days ago. Insist a bit more, I'm sure some relevant mirage people will end up answering.

I'm closing and I'll let some of the @mirage crew (@yomimono , @samoht ?) take that discussion on the cstruct bug tracker.

**Comment by pmetzger** [comment]
In general, I favor being much more detailed in reporting about the mechanism used to try to contact the maintainers before giving up...
