### ISSUE TITLE
CalendarLib

### ISSUE THREAD

**Issue by loxs** [ocaml-community/meta#20]
## Propose to move a project to ocaml-community ##

**Project name:**
Calendar/CalendarLib

**Initial author(s):**
Copyright © 2003-2011 Julien Signoles

**Current URL:**
[http://calendar.forge.ocamlcore.org](http://calendar.forge.ocamlcore.org)

**License:**
 LGPL (version 2.1), with the usual OCaml linking exception.

**Description:**
The Calendar Library (Calendar for short) is an Objective Caml library for handling dates and times in your program.

**Do the current maintainer(s) agree with the move:**
There is an email listed in the README
I haven't yet contacted Julien, as I'm a bit shy about it. I'd be very happy if some more established member of the community does the initial contact.

The current issue tracker/website of the project seems abandoned and we haven't seen new releases since 2014.

**New maintainer:**

I volunteer to be the new maintainer if Julien doesn't want to continue maintaining the library.
I already have new features in the pipeline which I don't know how to contribute (especially since the library doesn't use git, pull-requests etc. and I don't know svn well. This is also the main reason for me proposing that we include the code in ocaml-community (I'd like a modern, standardized workflow)

**Comment by pmetzger** [comment]
> I haven't yet contacted Julien, as I'm a bit shy about it. I'd be very happy if some more established member of the community does the initial contact.

I would suggest contacting him and pointing him at https://github.com/ocaml-community/meta/ so he can read for himself what it is that we do. I suspect no one would be more motivated to get the move performed than yourself.

As for the maintenance after that, I'm sure we can get a group willing to do that, a calendar library seems like a useful enough thing.

**Comment by loxs** [comment]
Email sent, will update here if I do or don't get a response.

**Comment by pmetzger** [comment]
I'd give them until the middle of next week at least, especially since it's about to be a weekend.

**Comment by signoles** [comment]
Hi,

I agree to transfer the maintainership of the Calendar library to ocaml-community. Feel free to ask questions about it in case of need.

Best,
julien

**Comment by loxs** [comment]
Thanks Julien!

Now I see there is already a fork with history converted (maybe) properly and some updates to the library as well here:

https://github.com/besport/calendar

I will write on their issue tracker with suggestion of consolidating effort here under ocaml-community.

Also I will review their changes in order to evaluate backwards compatibility etc.

**Comment by Drup** [comment]
Very good initiative @loxs, calendarLib is a very nice library that deserves some refreshing. Do you have some sort of roadmap in mind ?

@signoles Do you want co-maintainship/access to the repository ?

**Comment by signoles** [comment]
If possible, yes. But I think that I won't contribute that much because of lack of time.

**Comment by jeromesimeon** [comment]
Great to see this library being picked up. Will the new ocaml-community effort consider additional requirements for libraries (case in point: parsing or printing dates in ISO 8601 format).

**Comment by loxs** [comment]
Here is the roadmap as I see it:

1. Figure out the Opam/BeSport situation. Do we need to do major things to not break existing code (for example rename the library  so that existing code doesn't break etc.)? Then update the opam package or create a new one etc. Btw who has the access rights to this?

2. Introduce some QOL improvements that I have done. Only new API calls like allow comparing dates like `Date.( d1 < d2)` etc.  and do a minor release ( 1.05 ). The purpose of this step is mostly to learn and get things going.

3. Do a major (2.0) release with the following:
   - Educate myself on calendar topics, figure out new realities, discuss with people and decide if we need to change something big (hopefully not).
   - Migrate to Dune
   - Fix/figure out the the outstanding bugs in the old tracker
   - Maybe do some needed refactoring because of new OCaml releases/dependencies
   - Figure out testing, maybe migrate to newer test framework and fix any bugs found.
   - Write more docs: mostly user friendly ones with examples.

This might be a breaking change if the community decides that it's worth fixing some of the off-by-one problems, or if BeSport introduced breaking changes which we decide to adopt (yes, their changes are probably better off for the 2.0 release)

4. 2.1 release with further improvements that I need like (de)serializers.

5. We'll see after that.

**Comment by loxs** [comment]
@jeromesimeon  - Definitely ISO 8601 is on my TODO list as I need it myself.

**Comment by loxs** [comment]
From what I see, BeSport's changes really do make sense, but they are probably better off for a 2.0 release, as they will change behavior of existing code (although it's more "correct", it might be unexpected)

**Comment by Drup** [comment]
@loxs Looks good. I hope you know what you stepped into, since calendars are known to a very thorny topic! :)

At this point, we only need to have a github repository, transfer it to one of the ocaml-community stewards (@pmetzger or myself, for example) and we will transfer it to the repository and give you and @signoles appropriate rights.

**Comment by loxs** [comment]
@Drup - Yeah, I intend to tread very carefully. 

@signoles - Please have a look at the BeSport fork and see how you like the representation of the commit history. If you approve, I'll take their fork (up to your last commit) and start from there, then act according to the above roadmap. 

If you do not approve, I'll have a look into reposturgeon and see what I can do with it.

Another possibility is if you do the transfer to git yourself, the way you like it/

**Comment by signoles** [comment]
I do approve (and the changes there seem fine).

**Comment by loxs** [comment]
@Drup transferred the new repository to you

**Comment by pmetzger** [comment]
Now that it is in, someone should go through sections 4 and 5 of [README.md](https://github.com/ocaml-community/meta/blob/master/README.md) (creating the CI, cleaning up the README, etc.)

**Comment by pmetzger** [comment]
BTW, you may need to ask me or Drup to turn on travis-ci.com for the repo, if so just yell.

**Comment by loxs** [comment]
I haven't done travis-ci integration before, if it's OK to take a bit longer, I'm willing to learn.
If you guys want it running ASAP, please do it.

I will revise the README (and convert it to Markdown) once I have access.

**Comment by pmetzger** [comment]
Look at the `.travis.yml` files for the other things in `ocaml-community`, I think they're all basically identical. You just have to add that to the root and I'll do the rest.

**Comment by pmetzger** [comment]
You've been invited to the repository now.

**Comment by loxs** [comment]
Added the `.travis.yml` file

**Comment by pmetzger** [comment]
Remember to add the proper links for the build status when you fix the README.md -- you can use the others as an example.

**Comment by Drup** [comment]
Repository is [migrated](https://github.com/ocaml-community/calendar), @loxs and @signoles have admin roles over the new repository. I believe we can close here and do whatever needs to be done on the [new bug tracker](https://github.com/ocaml-community/calendar/issues)!

**Comment by pmetzger** [comment]
Should we add @signoles to CODEOWNERS or not? Up to you, @signoles.
