### ISSUE TITLE
The organization does not list any (public) members (at least to non-members)

### ISSUE THREAD

**Issue by loxs** [ocaml-community/meta#21]
Is this on purpose or just forgot to enable option?

It's even linked in the manifest, where it leads to an empty page.

**Comment by pmetzger** [comment]
I think it's a question of individual people setting themselves to list themselves. I can't force them to make themselves visible. I'll change my own visibility right now.

**Comment by pmetzger** [comment]
I believe @Drup has also changed his visibility.

**Comment by Drup** [comment]
@loxs You are not an org member. Org members are people that will work on all repositories. You only have rights over one repositories, and are thus consider an outside collaborator. This way is simpler for a bunch of reasons, but if you disagree, please discuss it [here]https://github.com/ocaml-community/meta/issues/11).

**Comment by pmetzger** [comment]
I think so.
