### ISSUE TITLE
FYI: list of projects I'm considering for submission

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/meta#25]
I just cut a list of projects I think would be good to migrate from mjambon to ocaml-community. I'd be the initial lead maintainer of these projects until we find someone else.

Let me know if you have immediate thoughts or reactions. I'll make a proper request for inclusion for each project when I have more time.

The list includes all the projects which match the following criteria:

* I'm the primary or original author. Copyright may be shared with past or current employers. All the projects come with a license that allows further development and distribution. To the best of my knowledge, nobody would be upset by moving them to a more community-oriented development style.
* The project is being used by others or is at least considered useful to a general audience (as opposed to a narrow domain of application).
* Maintaining the project doesn't require highly specialized domain knowledge. Any advanced OCaml programmer would have enough technical knowledge to contribute to the project.
* Help is needed primarily for maintenance tasks more than bold new features. This includes sorting issues, reviewing pull requests, managing releases, and helping and encouraging new contributors.

This is the list of projects I'm considering for migration:

* [atd](https://github.com/mjambon/atd)
* [biniou](https://github.com/mjambon/biniou)
* [caml2html](https://github.com/mjambon/caml2html)
* [cmitomli](https://github.com/mjambon/cmitomli)
* [cppo](https://github.com/mjambon/cppo)
* [dum](https://github.com/mjambon/dum)
* [dune-starter](https://github.com/mjambon/dune-starter)
* [dutop](https://github.com/mjambon/dutop)
* [easy-format](https://github.com/mjambon/easy-format)
* [ocamlscript](https://github.com/mjambon/ocamlscript)
* [sampl](https://github.com/mjambon/sampl)
* [wcl](https://github.com/mjambon/wcl)
* [yojson](https://github.com/mjambon/yojson)

**Comment by pmetzger** [comment]
This is great! I would suggest that we start with just a couple of the above in order to get the process for moving them smoothed out, and then you can do the others at will. Given the size of your proposed contributions, it would make sense to give you direct access to the overall repo.

**Comment by Drup** [comment]
That's a lot of projects, and some of them are quite old and not very used. I think we should try to think of which projects are still relevant in today's OCaml landscape and are important to the community. and only migrate those to ocaml-community, and make sure that each one has active maintainers. Projects like `cppo`, `yojson` or `atd` very clearly qualifies, `wcl` might not.

**Comment by mjambon** [comment]
The most used projects are also the most demanding in terms of maintenance, so I have no problem with that kind of cut-off.

I think the short list of projects that are clearly used directly or as dependencies is:
* atd
* biniou
* cppo
* dune-starter (might get obsolete soon)
* easy-format
* ocamlscript (not sure)
* yojson

**Comment by Drup** [comment]
I think dune-starter will probably get obsolete soon (@rgrinberg ?) so probably not. `ocamlscript` doesn't seem very used, and seem to depends on camlp4, so that's probably a no-go.

I'm personally not a fan of easy-format, and think it should be replaced by fmt, but that's just my opinion (and it's a dependency of most of the other ones, so it's debatable).

**Comment by mjambon** [comment]
For ocamlscript, it's more that it supports camlp4. We could remove this support (and dependency) and release a new major version.

**Comment by mjambon** [comment]
> I'm personally not a fan of easy-format, and think it should be replaced by fmt, but that's just my opinion (and it's a dependency of most of the other ones, so it's debatable).

I certainly don't want to force people to maintain software they don't like. How do we figure out if there are enough people willing to maintain a given package?

**Comment by rgrinberg** [comment]
`$ dune init` will certainly provide templates for dune projects. If that's all that dune-starter does, then I guess it's not really needed.

**Comment by pmetzger** [comment]
`cppo` and `yojson` are certainly uncontroversial in that people are using them daily. (Hell, I've used cppo quite a bit.) I'd suggest we start there and move down the list a bit at a time. Anyone object?

**Comment by mjambon** [comment]
ok, let's transfer (cppo)[https://github.com/mjambon/cppo] first. For this, please grant me the permission to create repositories on `ocaml-community`, [either by making me an Owner or by allowing this for all organization members](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/).

**Comment by pmetzger** [comment]
@mjambon Given the amount of stuff you potentially would want to deal with, I've sent you an organization membership invite, it seems easiest.

**Comment by mjambon** [comment]
Thanks @pmetzger, cppo is transferred. I'm transferring yojson too.

**Comment by Drup** [comment]
@mjambon I suggest you open a topic on discourse advertising your search for new maintaners for all these projects and pointing to the bug reports. You should reach a wider audience that way.

**Comment by XVilka** [comment]
See https://discuss.ocaml.org/t/the-easy-format-package-a-dependency-of-js-of-ocaml-still-uses-jbuilder-and-the-author-states-on-his-github-profile-that-he-no-longer-maintains-it-will-this-be-an-issue/3980

**Comment by pmetzger** [comment]
If the notion is that easy-format should get moved to ocaml-community, I have no objections.
