### ISSUE TITLE
linenoise

### ISSUE THREAD

**Issue by c-cube** [ocaml-community/meta#26]
## Propose to move a project to ocaml-community ##

**Project name:** linenoise

**Initial author(s):** Edgar Aroutiounian (fxfactorial)

**Current URL:** https://github.com/fxfactorial/ocaml-linenoise

**License:** BSD

**Description:** self-contained readline alternative, without dependencies on system libraries

**Do the current maintainer(s) agree with the move:** yes, see https://github.com/fxfactorial/ocaml-linenoise/issues/9

**New maintainer:** @c-cube (been maintaining it for a while)

**Comment by pmetzger** [comment]
Seems good to me! Do you need any additional privileges on the ocaml-community side at this point or can you arrange the migration on your own?

**Comment by c-cube** [comment]
On the ocaml-community side I think it should work (if sufficiently many people agree), but I do need the admin rights on Edgar's repo to transfer ownership cleanly, I think.

**Comment by pmetzger** [comment]
@c-cube I see there's now an empty repository for linenoise? Perhaps that wasn't your intent?

**Comment by c-cube** [comment]
Done! thanks again to @pmetzger and @fxfactorial :sparkles:

**Comment by c-cube** [comment]
I think it's fine:

- dune
- travis
- opam package
- compiles on last version
- updated references to the old website
