### ISSUE TITLE
cppo - looking for new maintainer

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/meta#27]
I already transferred cppo to ocaml-community. We're looking for a volunteer to take over its maintenance. No new features are planned and bugs are infrequently found. The maintainers will need to ensure that cppo remains compatible with old and new versions of OCaml. Currently, 57 public opam packages depend on cppo.

**Project name:** cppo

**Initial author(s):** Martin Jambon

**Current URL:** already transferred

**License:** BSD

**Description:** C-style preprocessor for OCaml

**Do the current maintainer(s) agree with the move:** yes

**New maintainer:** looking for a volunteer

**Comment by mjambon** [comment]
I added a `CODEOWNERS` file. I left a question about Travis at https://github.com/ocaml-community/cppo/issues/64, please let me know what to do.

**Comment by pmetzger** [comment]
Should this now be closed?
