### ISSUE TITLE
yojson - looking for new maintainer

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/meta#28]
Yojson is a widely-used json parsing and pretty-printing library. It was designed as the runtime for [atdgen](https://github.com/mjambon/atd) with performance in mind. If anyone would like to become the new lead maintainer, please step forward.

**Project name:** yojson

**Initial author(s):** Martin Jambon

**Current URL:** already transferred to ocaml-community

**License:** BSD

**Description:** json parsing and printing library for OCaml designed to be used by type-aware code generators

**Do the current maintainer(s) agree with the move:** yes

**New maintainer:** looking for a volunteer

**Comment by anuragsoni** [comment]
Just a note for anyone volunteering to be the new lead maintainer, if you need help with packaging and/or other tasks related to the ecosystem feel free to reach out and I'll help. This goes for other packages in `ocaml-community` as well

**Comment by pmetzger** [comment]
Should this now be closed?

**Comment by mjambon** [comment]
yes
