### ISSUE TITLE
biniou

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/meta#31]
## Propose to move a project to ocaml-community ##

**Project name:** biniou

**Initial author(s):** Martin Jambon (me)

**Current URL:** https://github.com/mjambon/biniou

**License:** BSD

**Description:** runtime for an extensible binary format. Usable in a safe manner via atdgen, see https://atd.readthedocs.io/en/latest/

**Do the current maintainer(s) agree with the move:** yes

**New maintainer:** looking for a volunteer

**Comment by pmetzger** [comment]
Do we want to wait to do the transfer until we have a volunteer, or should we start earlier?

**Comment by mjambon** [comment]
As far as I'm concerned, the earlier the better. I think it's a better place for contributors than my personal GitHub account.

**Comment by pmetzger** [comment]
@rgrinberg Do you intend to take over biniou as well?

**Comment by rgrinberg** [comment]
Yes. I plan to maintain it passively as well.

**Comment by pmetzger** [comment]
@mjambon In that case, we have a maintainer.
