### ISSUE TITLE
easy-format

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/meta#32]
## Propose to move a project to ocaml-community ##

**Project name:** easy-format

**Initial author(s):** Martin Jambon (me)

**Current URL:** https://github.com/mjambon/easy-format

**License:** BSD

**Description:** functional pretty-printing library

**Do the current maintainer(s) agree with the move:** yes

**New maintainer:** looking for a volunteer

**Comment by rgrinberg** [comment]
Just as an side, including this project under ocaml-community does not mean these projects need to be recommended. It's just recognition that continuous maintenance of this project is important to the general health of the ecosystem. 

I'm willing to volunteer with making small fixes and regular releases for this project and biniou.

**Comment by pmetzger** [comment]
Cool. If @mjambon is happy, and @rgrinberg is happy maintaining for now, lets do it! Could @mjambon start by transferring the repository, and then after that, I presume @rgrinberg can go through the adoption checklist in https://github.com/ocaml-community/meta/blob/master/README.md ?

**Comment by mjambon** [comment]
It's transferred!

**Comment by rgrinberg** [comment]
I read the README. Will make sure to update things once I have some spare maintenance cycles for easy-format and biniou.

**Comment by pmetzger** [comment]
@rgrinberg Do you intend to take over biniou as well? If so, please comment on that issue if you can.

**Comment by pmetzger** [comment]
@mjambon Thank you!
