### ISSUE TITLE
iso8601

### ISSUE THREAD

**Issue by c-cube** [ocaml-community/meta#33]
## Propose to move a project to ocaml-community ##

**Project name:** ISO8601

**Initial author(s):** @sagotch

**Current URL:** https://github.com/sagotch/ISO8601.ml

**License:** MIT

**Description:** parser and printer for the standard representation of datetime

**Do the current maintainer(s) agree with the move:** [yes](https://github.com/sagotch/ISO8601.ml/issues/13#issuecomment-529811512)

**New maintainer:** I (@c-cube) am willing to do it, not expecting a lot of new features to be added.

**Comment by Drup** [comment]
Why not clean up/integrate into calendar's code base instead ?

**Comment by c-cube** [comment]
@Drup no thanks. Not the same thing. ISO8601 is a simple and lightweight library for parsing/printing, that's all. It's a dependency I never think twice before adding.

**Comment by pmetzger** [comment]
Given that @c-cube is willing to maintain it, I think this is fine. @c-cube, just move the repository over and do what's necessary.

**Comment by Drup** [comment]
Well, it would be nice to at least make them compatible somehow .... (one using the other, whichever the direction)

**Comment by c-cube** [comment]
the compatibility is in the standard. But sure, calendar could use ISO8601, as its scope is much wider.
