### ISSUE TITLE
Move ocaml-language-server to ocaml-community organization

### ISSUE THREAD

**Issue by darinmorrison** [ocaml-community/meta#34]
## Propose to move a project to ocaml-community ##

**Project name:** ocaml-language-server

**Initial author(s):** Darin Morrison (me)

**Current URL:** https://github.com/ocaml-lsp/ocaml-language-server

**License:** Apache 2.0

**Description:** Language server for OCaml implemented in TypeScript using MS component libs

**Do the current maintainer(s) agree with the move:** Yes

**New maintainer:** looking for additional maintainers to help with project maintenance

**Comment by c-cube** [comment]
This seems to be a typescript project, what are the benefits compared to Merlin's LSP mode?

**Comment by pmetzger** [comment]
I am a bit confused myself; I did think Merlin already implemented an LSP server for OCaml that was used by a lot of people. @darinmorrison can you explain a bit about what distinguishes this LSP implementation?

**Comment by pmetzger** [comment]
(BTW, I don't want to be discouraging; the question isn't rhetorical.)

**Comment by darinmorrison** [comment]
I created this issue because I wanted to help ensure the server continues to be maintained as long as people still need it. In the long run, if the LSP support implemented in merlin is viable, that's probably the better option and new users should be encouraged to use that instead.

Based on my experience working with merlin and the ocaml tooling and having implemented the earlier server, I think I would go in a different direction than implementing LSP directly in merlin, but that's a technical discussion I'd get into detail about in this thread. I'll just say I think that sort of monolithic approach is going to become increasingly difficult to maintain, but I hope it works out.

I'm going to close this issue since on further reflection the project probably isn't a great fit given the current implementation (e.g., written in typescript). For those still using the server, I'll try to keep it usable but I don't have the resources to make it a priority; if you still use it and for whatever reason it is important to you, the best thing to do is to get involved and create issues and PRs in the repo linked in the original post. I'm happy to add contributors to the project.

Thanks for responding and considering the request.
