### ISSUE TITLE
Consider mirroring on codeberg/notabug/framagit (github alternative)

### ISSUE THREAD

**Issue by kanishka-work** [ocaml-community/meta#36]
Consider mirroring to and accepting contributions to some or all of this org's repos on codeberg, notabug, or framagit. Thanks for considering. Feel free to close if this is not of interest.

**Comment by pmetzger** [comment]
I'm not sure what the advantage of this would be, and it would mean getting pull requests in multiple places and having to coordinate developers across multiple platforms.

**Comment by kanishka-work** [comment]
There's no practical advantage. It's purely an ideological preference of mine, probably <5% of people have similar views to me on GitHub.

**Comment by pmetzger** [comment]
It seems to me to be too difficult to maintain multiple simultaneous parallel repositories.
