### ISSUE TITLE
Move Camomile to ocaml-community

### ISSUE THREAD

**Issue by toots** [ocaml-community/meta#39]
## Propose to move a project to ocaml-community ##

**Project name:** Camomile

**Initial author(s):** https://github.com/yoriyuki

**Current URL:** https://github.com/yoriyuki/Camomile

**License:** LGPL 2 or above

**Description:** Unicode library for OCaml

**Do the current maintainer(s) agree with the move:** yes

**New maintainer:** Romain Beauxis plus anyone interested to contribute

Camomile is very valuable library in the OCaml ecosystem. It is the only one that provides output capacities in legacy string encodings. The code has been in need of some love, most importantly an update to support OCaml 5.

The move and initial development plans have been discussed and approved by the original author.

**Comment by toots** [comment]
I'm moving on with a fork over at https://github.com/savonet/Camomile but would be happy to move it here whenever possible.

**Comment by pmetzger** [comment]
I see no reason it couldn't be moved. Anyone else object?

**Comment by toots** [comment]
Great, gonna initiate the transfer @pmetzger

**Comment by toots** [comment]
Ha no sorry I need permission to create a repository with the org before initiating the transfer.

**Comment by tmcgilchrist** [comment]
I came across this issue after trying to get camomile building on OCaml 5 and finding this PR https://github.com/savonet/Camomile/pull/1. Will this project get moved into @ocaml-community from the original https://github.com/yoriyuki/Camomile repository?

**Comment by toots** [comment]
For sure. I'm still waiting for the repository to be created and/or to get the proper admin access to do it. We will be making releases regardless but I would rather make it clear that the repository of open to community contributions.

**Comment by pmetzger** [comment]
Sorry. I've been busy for a few months. Can you tell me exactly what you need me to do and I'll do it?

**Comment by toots** [comment]
Welcome back! Either give me the permission to create the repo or else create the repo and add me as admin. Permission to edit repos would be great as I'm also not getting full access on `sedlex` to e.g. set actions, change settings etc. Thanks!

**Comment by c-cube** [comment]
Sorry to jump in, I added you to a maintainer role. Please say if it's not enough to create the repo :)

**Comment by toots** [comment]
Hi @c-cube thanks for the intervention! Unfortunately, this only applies to this repository, I am still unable to create the new camomile repository.

**Comment by c-cube** [comment]
Ok, I guess we have to add you as a team member? I'm really not well versed in github teams… :/

**Comment by toots** [comment]
Yeah or else you can create the repo and invite me as a collaborator on it.

**Comment by toots** [comment]
I'm not allowed to do it either.

**Comment by c-cube** [comment]
But if we create a repo here, it's not transferred anymore, is it? I guess it can just become the new one, but the old one would remain as is without redirecting here?

**Comment by c-cube** [comment]
Alright, enough friction, I've invited you to the organization.

**Comment by toots** [comment]
Awesome. Repo transfered!

**Comment by pmetzger** [comment]
Honestly, given all the things @toots does it was very reasonable to make him a member and should have been done long ago.
