### ISSUE TITLE
Request to move ocaml-mariadb to ocaml-community

### ISSUE THREAD

**Issue by paurkedal** [ocaml-community/meta#40]
## Propose to move a project to ocaml-community ##

**Project name:**

OCaml-MariaDB, ocaml-mariadb, mariadb (opam)

**Initial author(s):**

Andre Nathan

**Current URL:**

https://github.com/andrenth/ocaml-mariadb

**License:**

MIT

**Description:**

OCaml-MariaDB provides Ctypes-based bindings for MariaDB, including its nonblocking API.  I think this is our best maintained client to MariaDB and MySQL, and the one use by [Caqti](https://github.com/paurkedal/ocaml-caqti) (maintained by me).

**Do the current maintainer(s) agree with the move:**

Yes, the move has been agreed between the original author, current maintainer, and me in andrenth/ocaml-mariadb#53.

**New maintainer:** 

I suggest @ygrek, who current has commit rights, and who I think will be making releases, and maybe myself as a backup, at least I plan to help out in the near future and with the move.

**Comment by pmetzger** [comment]
Seems okay to me. If we request a transfer, will @andrenth approve it?

**Comment by andrenth** [comment]
I will :)

**Comment by pmetzger** [comment]
Now if I can only remember how do do the request! :)

**Comment by pmetzger** [comment]
Okay, @andrenth you will want to do what is in https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account and then post here to say the request has been made.

**Comment by andrenth** [comment]
It says "You don’t have the permission to create public repositories on ocaml-community". Not sure if I did something wrong.

**Comment by pmetzger** [comment]
Did you specify a new owner (ocaml-community)?

**Comment by andrenth** [comment]
Yes:

![image](https://github.com/user-attachments/assets/2fa5d8ea-ed95-48ba-bf11-31e0a6534eb3)

**Comment by andrenth** [comment]
The [repository transfer docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) say "_To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization._" so I'm not sure how pro proceed. Maybe it's simpler to fork my repository and then I archive it?

**Comment by pmetzger** [comment]
No. We have made this work in the past. Give me a bit to figure it out.

**Comment by pmetzger** [comment]
@andrenth I've sent you an invitation — once you accept that, you should be able to initiate the transfer.

**Comment by andrenth** [comment]
Done

**Comment by pmetzger** [comment]
@paurkedal Okay, next steps will be to get the maintainers added to the moved repository, get the CI set up, etc.

**Comment by paurkedal** [comment]
Thanks for the effort.  I created ocaml-community/ocaml-mariadb#55 to track the completion.

**Comment by paurkedal** [comment]
Looks like we might need help with the initial permissions after the move (see discussion the above issue).  Can you make @ygrek admin?

**Comment by pmetzger** [comment]
I made @ygrek an admin of the ocaml-mariadb repository.

**Comment by pmetzger** [comment]
Okay, so what's left before we can close this issue?

**Comment by ygrek** [comment]
i think it is all good, further steps tracked in https://github.com/ocaml-community/ocaml-mariadb/issues/55
