### ISSUE TITLE
Is the Travis CI recommendation still relevant?

### ISSUE THREAD

**Issue by paurkedal** [ocaml-community/meta#41]
The README suggests setting up Travis CI for imported projects, however the file was last updated 6 years ago, and things have changed since.  In particular I found https://earthly.dev/blog/migrating-from-travis/ via Wikipedia and https://discuss.ocaml.org/t/best-practices-for-continuous-integration-ci-in-2023/12380.  So, is it time to replace the reference to Travis CI with a more generic suggestion or a different recommendation?

**Comment by pmetzger** [comment]
No, we should not be using Travis now, but rather Github's built in stuff. @liyishuai has been helping get some of that cleaned up.

Please feel free to do a pull request to update the README.
