### ISSUE TITLE
clangml - OCaml Clang bindings

### ISSUE THREAD

**Issue by XVilka** [ocaml-community/meta#7]
Seems abandoned but a great deal (not sure why Clang project doesn't adapt them)
https://github.com/Antique-team/clangml

**Comment by pmetzger** [comment]
I don't think the Clang/LLVM project generally has bindings for languages other than C and C++. (LLVM has official OCaml bindings but that's different from Clang.)

The license is also unusual, though that's not a problem for _us_, though it might be for the Clang people themselves.

Anyway, would you like to contact the authors and find out if they're willing to allow us to adopt the package? And would you be willing to handle the work?

**Comment by pmetzger** [comment]
@XVilka any progress?

**Comment by gasche** [comment]
(cc @UnixJunkie)

**Comment by pmetzger** [comment]
@UnixJunkie Any possibility of you asking? Also, is it possible to get it relicensed?

**Comment by UnixJunkie** [comment]
@xrival Xavier, people are asking things about clangml.

**Comment by xrival** [comment]
Bonjour François,

Merci, je n'avais pas reçu les notifications !

Cela tombe bien, je voulais justement demander à Thierry Martinez et
Sébastien Hinderer si nous pouvions porter clangml aux versions plus
récentes de clang. Je vais aussi poser la question de la license.

Xavier.

**Comment by xrival** [comment]
Indeed, the project gets upgrades when needed for our research.
As of today, we use clangml on a regular basis but are not upgrading it as the current version does all we need it to. But we are considering making it compatible with the latest versions of clang.

There is of course no issue if you would like to use it or to contribute to it. Just let me know what you need or plan.

Best,

Xavier.

**Comment by UnixJunkie** [comment]
So, the conclusion is: not abandoned and not unmaintained.
I think you can close this, and post an issue in 
https://github.com/Antique-team/clangml/issues
if you need an updated version.

**Comment by XVilka** [comment]
@UnixJunkie I opened last year already: https://github.com/Antique-team/clangml/issues/66 and https://github.com/Antique-team/clangml/issues/67

**Comment by XVilka** [comment]
Also no reaction to this PR: https://github.com/Antique-team/clangml/pull/68

**Comment by UnixJunkie** [comment]
It's not very lively maybe, but it is used by @xrival and his students.
Moreover, @shindere and @thierry-martinez both know how to update it to a more recent clang version.
Personally, I am no more involved with this project.

**Comment by gasche** [comment]
@XVilka (and others): I got in touch with @xrival to try to explain the context better. They will be discussing what they want for the project sometime next week, and I think we should hear back after that.

**Comment by gasche** [comment]
(No matter what they prefer regarding ocaml-community, I pointed out that it would be nicer if the project got reactive maintenance, and I think they now understand that.)

**Comment by XVilka** [comment]
@pmetzger https://github.com/Antique-team/clangml/issues/69

**Comment by thierry-martinez** [comment]
clangml.4.0.0beta1 is out: https://tmartine.gitlabpages.inria.fr/clangml/

**Comment by pmetzger** [comment]
Given that this isn't unmaintained and the maintainers don't want to move it to ocaml-community I'm going to close this.
