### ISSUE TITLE
bigstring

### ISSUE THREAD

**Issue by c-cube** [ocaml-community/meta#8]
It'd be nice to move [bigstring](https://github.com/c-cube/ocaml-bigstring/) here, it's really mostly a compat package

**Comment by pmetzger** [comment]
Seems fine by me. Isn't there a current PR about pulling bigstring into the stdlib, or is it a different bigstring? See: https://github.com/ocaml/ocaml/pull/1961

**Comment by pmetzger** [comment]
I've just sent you an invite to the organization, it should be in your email.

**Comment by Drup** [comment]
@c-cube What's the relation between this and bigstringaf ?

**Comment by c-cube** [comment]
- bigstringaf is more recent and it includes some C stuff, afaik.
- The OCaml PR doesn't look like it's going to be approved, imho (Xavier doesn't like it, right?)
- this package would be a good place to have retrocompatible support for `map_file`, whether it comes from `Bigarray` or from `Unix`, but I have 0 time for that

**Comment by pmetzger** [comment]
Anyway, what's our next step?

**Comment by c-cube** [comment]
Close the topic, I suppose. It's not a library important enough to the community.
